### ISSUE TITLE
Support for custom sort function

### ISSUE THREAD

**Issue by t-fritsch** [Siilwyn/prettier-plugin-css-order#16] opened 2022-11-04 23:25 UTC
Thanks for the great work on this plugin ! I've been looking for a plugin like this one since the death of https://github.com/mrmlnc/vscode-csscomb 

Anyway I wonder if there would be a way to allow custom sort functions in the `order` option since this is something that `css-declaration-sorter` allows (https://github.com/Siilwyn/css-declaration-sorter#order)

Following `css-declaration-sorter` examples (https://github.com/Siilwyn/css-declaration-sorter/blob/master/examples/custom-order-function.md#custom-order-function) I've tried something like this : 
```js
// .prettierrc.cjs
const myOrder = ['margin', 'border', 'padding'];

module.exports = {
	singleQuote: true,
	trailingComma: 'es5',
	endOfLine: 'lf',
	arrowParens: 'avoid',
	order: (a, b) => myOrder.indexOf(a) - myOrder.indexOf(b),
};
```

This doesn't work :
```
Error: Invalid order value. Expected "alphabetical", "concentric-css" or "smacss", but received undefined.
	at Normalizer._applyNormalization (/xxxxxx/xxxxxxx/node_modules/prettier/index.js:6046:61)
```

**Comment by t-fritsch** [comment] 2022-11-05 02:02
looking at the forks I found https://github.com/003marek/prettier-plugin-css-order and https://github.com/003marek/css-declaration-sorter by @003marek 

Instead of allowing to pass function it tries to add the possibilty to pass an array of sorted css rules.

Unfortunately I couldn't make it work (prettier extension hangs when formatting a css file)

I tried to debug it with no luck but maybe this will help

**Comment by t-fritsch** [comment] 2022-11-17 15:15
If you have any idea on the best way to implement this @Siilwyn I'd be happy to try a PR 🙏 (I've never developed a prettier plugin before so I'm quite lost here)

**Comment by Siilwyn** [comment] 2022-11-17 18:48
👋 first of all sorry for the late reply, and awesome to see your contributions!

Thing is I want to see if this can be solved without changing the core module (css-declaration-sorter) but allowing the function instead... It's not working because I'm using sync-threads to run async code which Prettier at the time of writing this code did not support.
In fact I made a todo/issue for replacing sync-threads with 'normal' code: https://github.com/Siilwyn/prettier-plugin-css-order/issues/1
Fixing that should also allow passing in a function I believe, I just have not found the time to look into this further. Feel free to do so though! Otherwise I'll probably get around to this some time later.

**Comment by Siilwyn** [comment] 2023-07-29 13:13
Circling back to this, Prettier 3 is out and we have async support now!
Sadly at the moment Prettier does not allow functions or arrays to be passed to an option if I understand correctly: https://github.com/prettier/prettier/blob/1942c0b9f9acd65ce523998c9193f1f9453b13a0/src/index.d.ts#L670-L675

Closing this for now as blocked by https://github.com/prettier/prettier/issues/14671

Please correct me if I'm wrong, thanks!

**Closed by Siilwyn** 2023-07-29 13:13 UTC

**Comment by t-fritsch** [comment] 2023-08-02 14:30
Hi @Siilwyn 

Thank you for the feedback

I managed to get custom order working by modifying `runAsWorker`'s call : in my prettier config I pass a JSON encoded Array. This JSON string is then parsed in the runAsWorker call to get the Array instance back and inject in pluginOptions.order a custom function that do the sorting according to the Array values. 

My code is not clean yet (I had to comment the "choices" section of the `order` option in `main.js` and I coded directly in node_modules folder 😅) it is also still based on 1.3 version (I saw you published a 2.0 version recently) but I'll try to submit a PR in the coming days.

**Comment by t-fritsch** [comment] 2023-08-02 21:00
OK, it seems that my fix for 1.3 wont be so simple to apply to 2.0 since the `src/sorter.js` file (the one that contained the `runAsWorker()`call) has been removed from this repo. 

It looks like the logic in it has been moved to css-declaration-sorter package, am I wrong @Siilwyn ?

**Comment by Siilwyn** [comment] 2023-08-03 11:49
The `runAsWorker` related code was a workaround for Prettier 2, it's been removed completely since Prettier 3 has async support now. No logic has been moved to the core package.

Custom sorting logic can be passed to the core package inside this function: https://github.com/Siilwyn/prettier-plugin-css-order/blob/main/src/main.mjs#L12

However the issue is that functions can't be passed as an option and neither can arrays: https://github.com/prettier/prettier/issues/14671

Could work around this with an extra option that accepts an JSON string but I 'm unsure if I like to have that in this package as it's quite 'hacky'.

**Comment by Siilwyn** [comment] 2023-08-03 11:50
I'm very curious though what custom order are you maintaining? The built-in options don't come close?
